# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sarellad/test_task

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sarellad/test_task

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sarellad/test_task/CMakeFiles /home/sarellad/test_task//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sarellad/test_task/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DailyPlanner

# Build rule for target.
DailyPlanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DailyPlanner
.PHONY : DailyPlanner

# fast build rule for target.
DailyPlanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/build
.PHONY : DailyPlanner/fast

birthday.o: birthday.cc.o
.PHONY : birthday.o

# target to build an object file
birthday.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/birthday.cc.o
.PHONY : birthday.cc.o

birthday.i: birthday.cc.i
.PHONY : birthday.i

# target to preprocess a source file
birthday.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/birthday.cc.i
.PHONY : birthday.cc.i

birthday.s: birthday.cc.s
.PHONY : birthday.s

# target to generate assembly for a file
birthday.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/birthday.cc.s
.PHONY : birthday.cc.s

daily_planner.o: daily_planner.cc.o
.PHONY : daily_planner.o

# target to build an object file
daily_planner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/daily_planner.cc.o
.PHONY : daily_planner.cc.o

daily_planner.i: daily_planner.cc.i
.PHONY : daily_planner.i

# target to preprocess a source file
daily_planner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/daily_planner.cc.i
.PHONY : daily_planner.cc.i

daily_planner.s: daily_planner.cc.s
.PHONY : daily_planner.s

# target to generate assembly for a file
daily_planner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/daily_planner.cc.s
.PHONY : daily_planner.cc.s

date.o: date.cc.o
.PHONY : date.o

# target to build an object file
date.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/date.cc.o
.PHONY : date.cc.o

date.i: date.cc.i
.PHONY : date.i

# target to preprocess a source file
date.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/date.cc.i
.PHONY : date.cc.i

date.s: date.cc.s
.PHONY : date.s

# target to generate assembly for a file
date.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/date.cc.s
.PHONY : date.cc.s

date_time.o: date_time.cc.o
.PHONY : date_time.o

# target to build an object file
date_time.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/date_time.cc.o
.PHONY : date_time.cc.o

date_time.i: date_time.cc.i
.PHONY : date_time.i

# target to preprocess a source file
date_time.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/date_time.cc.i
.PHONY : date_time.cc.i

date_time.s: date_time.cc.s
.PHONY : date_time.s

# target to generate assembly for a file
date_time.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/date_time.cc.s
.PHONY : date_time.cc.s

event.o: event.cc.o
.PHONY : event.o

# target to build an object file
event.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/event.cc.o
.PHONY : event.cc.o

event.i: event.cc.i
.PHONY : event.i

# target to preprocess a source file
event.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/event.cc.i
.PHONY : event.cc.i

event.s: event.cc.s
.PHONY : event.s

# target to generate assembly for a file
event.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/event.cc.s
.PHONY : event.cc.s

full_name.o: full_name.cc.o
.PHONY : full_name.o

# target to build an object file
full_name.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/full_name.cc.o
.PHONY : full_name.cc.o

full_name.i: full_name.cc.i
.PHONY : full_name.i

# target to preprocess a source file
full_name.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/full_name.cc.i
.PHONY : full_name.cc.i

full_name.s: full_name.cc.s
.PHONY : full_name.s

# target to generate assembly for a file
full_name.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/full_name.cc.s
.PHONY : full_name.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DailyPlanner.dir/build.make CMakeFiles/DailyPlanner.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DailyPlanner"
	@echo "... birthday.o"
	@echo "... birthday.i"
	@echo "... birthday.s"
	@echo "... daily_planner.o"
	@echo "... daily_planner.i"
	@echo "... daily_planner.s"
	@echo "... date.o"
	@echo "... date.i"
	@echo "... date.s"
	@echo "... date_time.o"
	@echo "... date_time.i"
	@echo "... date_time.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... full_name.o"
	@echo "... full_name.i"
	@echo "... full_name.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

